### ISSUE TITLE
['file_path_contours_touching'] not in index

### ISSUE THREAD

**Issue by HAOYU-LI** [neptune-ml/data-science-bowl-2018#43]
Issue encountered when running : 

`neptune send main.py --worker gcp-gpu-medium --environment pytorch-0.2.0-gpu-py3 -- train_evaluate_predict_pipeline --pipeline_name unet_multitask`

I'm sure that I use the latest version of code. Any suggestions?

> Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/deepsense/neptune/job_wrapper.py", line 113, in <module>
    execute()
  File "/usr/local/lib/python3.6/dist-packages/deepsense/neptune/job_wrapper.py", line 109, in execute
    execfile(job_filepath, job_globals)
  File "/usr/local/lib/python3.6/dist-packages/past/builtins/misc.py", line 82, in execfile
    exec_(code, myglobals, mylocals)
  File "main.py", line 181, in <module>
    action()
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "main.py", line 153, in train_evaluate_predict_pipeline
    _train_pipeline(pipeline_name, validation_size)
  File "main.py", line 80, in _train_pipeline
    pipeline.fit_transform(data)
  File "/neptune/steps/base.py", line 92, in fit_transform
    step_inputs[input_step.name] = input_step.fit_transform(data)
  File "/neptune/steps/base.py", line 92, in fit_transform
    step_inputs[input_step.name] = input_step.fit_transform(data)
  File "/neptune/steps/base.py", line 92, in fit_transform
    step_inputs[input_step.name] = input_step.fit_transform(data)
  [Previous line repeated 1 more times]
  File "/neptune/steps/base.py", line 98, in fit_transform
    step_output_data = self._cached_fit_transform(step_inputs)
  File "/neptune/steps/base.py", line 109, in _cached_fit_transform
    step_output_data = self.transformer.fit_transform(**step_inputs)
  File "/neptune/steps/base.py", line 242, in fit_transform
    return self.transform(*args, **kwargs)
  File "/neptune/steps/preprocessing.py", line 50, in transform
    y_ = meta[self.y_columns].values
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py", line 2133, in __getitem__
    return self._getitem_array(key)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py", line 2177, in _getitem_array
    indexer = self.loc._convert_to_indexer(key, axis=1)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/indexing.py", line 1269, in _convert_to_indexer
    .format(mask=objarr[mask]))
KeyError: "['file_path_contours_touching'] not in index"

**Comment by mpsampat** [comment]
Yup i got the same error: 

  |  
-- | --
42.397721 | 0%\| \| 0/531 [00:00<?, ?it/s]  1%\| \| 4/531 [00:00<00:22, 23.06it/s]  1%\|▏ \| 7/531 [00:00<00:23, 21.96it/s]  3%\|▎ \| 14/531 [00:00<00:20, 25.75it/s]  4%\|▎ \| 19/531 [00:00<00:18, 28.28it/s]  4%\|▍ \| 22/531 [00:00<00:21, 23.64it/s]  5%\|▌ \| 28/531 [00:00<00:17, 28.89it/s]  6%\|▌ \| 32/531 [00:01<00:18, 26.98it/s]  7%\|▋ \| 36/531 [00:01<00:16, 29.48it/s]  8%\|▊ \| 41/531 [00:01<00:14, 33.41it/s]  8%\|▊ \| 45/531 [00:01<00:18, 26.77it/s]  9%\|▉ \| 50/531 [00:01<00:16, 28.50it/s]  10%\|█ \| 54/531 [00:01<00:18, 25.54it/s]  11%\|█ \| 57/531 [00:02<00:26, 18.16it/s]  11%\|█▏ \| 60/531 [00:02<00:23, 19.69it/s]  12%\|█▏ \| 65/531 [00:02<00:20, 22.49it/s]  13%\|█▎ \| 68/531 [00:02<00:19, 23.78it/s]  13%\|█▎ \| 71/531 [00:02<00:21, 21.71it/s]  14%\|█▍ \| 75/531 [00:02<00:19, 23.58it/s]  15%\|█▍ \| 78/531 [00:02<00:18, 24.14it/s]  15%\|█▌ \| 81/531 [00:03<00:17, 25.51it/s]  17%\|█▋ \| 88/531 [00:03<00:16, 27.65it/s]  18%\|█▊ \| 93/531 [00:03<00:15, 27.81it/s]  18%\|█▊ \| 97/531 [00:03<00:15, 28.40it/s]  19%\|█▉ \| 100/531 [00:03<00:16, 25.39it/s]  20%\|█▉ \| 104/531 [00:03<00:15, 28.46it/s]  20%\|██ \| 108/531 [00:03<00:13, 30.46it/s]  21%\|██ \| 112/531 [00:04<00:13, 31.76it/s]  22%\|██▏ \| 116/531 [00:04<00:13, 31.12it/s]  23%\|██▎ \| 120/531 [00:04<00:12, 32.66it/s]  24%\|██▎ \| 125/531 [00:04<00:11, 35.75it/s]  24%\|██▍ \| 129/531 [00:04<00:12, 31.34it/s]  25%\|██▌ \| 133/531 [00:04<00:11, 33.40it/s]  26%\|██▌ \| 139/531 [00:04<00:10, 38.21it/s]  27%\|██▋ \| 146/531 [00:04<00:09, 40.65it/s]  28%\|██▊ \| 151/531 [00:05<00:12, 31.26it/s]  29%\|██▉ \| 155/531 [00:05<00:13, 28.51it/s]  30%\|██▉ \| 159/531 [00:05<00:12, 30.61it/s]  31%\|███ \| 163/531 [00:05<00:13, 27.28it/s]  31%\|███▏ \| 167/531 [00:05<00:12, 29.83it/s]  32%\|███▏ \| 171/531 [00:05<00:11, 30.87it/s]  33%\|███▎ \| 176/531 [00:05<00:10, 32.70it/s]  34%\|███▍ \| 183/531 [00:06<00:08, 38.87it/s]  35%\|███▌ \| 188/531 [00:06<00:09, 34.41it/s]  37%\|███▋ \| 197/531 [00:06<00:08, 40.97it/s]  38%\|███▊ \| 202/531 [00:06<00:07, 41.62it/s]  39%\|███▉ \| 207/531 [00:06<00:07, 43.73it/s]  40%\|███▉ \| 212/531 [00:06<00:07, 45.09it/s]  42%\|████▏ \| 223/531 [00:06<00:06, 48.26it/s]  43%\|████▎ \| 229/531 [00:06<00:06, 47.84it/s]  44%\|████▍ \| 234/531 [00:07<00:07, 38.45it/s]  45%\|████▌ \| 240/531 [00:07<00:08, 36.20it/s]  46%\|████▌ \| 244/531 [00:07<00:10, 28.03it/s]  47%\|████▋ \| 250/531 [00:07<00:08, 31.68it/s]  48%\|████▊ \| 254/531 [00:07<00:09, 28.53it/s]  49%\|████▊ \| 258/531 [00:08<00:14, 18.69it/s]  50%\|████▉ \| 263/531 [00:08<00:11, 22.96it/s]  52%\|█████▏ \| 274/531 [00:08<00:08, 29.97it/s]  53%\|█████▎ \| 280/531 [00:08<00:08, 28.23it/s]  54%\|█████▍ \| 286/531 [00:08<00:07, 31.67it/s]  55%\|█████▍ \| 292/531 [00:08<00:06, 36.28it/s]  56%\|█████▌ \| 297/531 [00:09<00:06, 33.95it/s]  57%\|█████▋ \| 302/531 [00:09<00:06, 34.81it/s]  58%\|█████▊ \| 307/531 [00:09<00:06, 33.72it/s]  59%\|█████▉ \| 312/531 [00:09<00:06, 35.15it/s]  60%\|█████▉ \| 316/531 [00:09<00:06, 34.66it/s]  61%\|██████ \| 322/531 [00:09<00:05, 37.54it/s]  62%\|██████▏ \| 330/531 [00:09<00:04, 42.43it/s]  63%\|██████▎ \| 336/531 [00:10<00:05, 35.63it/s]  64%\|██████▍ \| 341/531 [00:10<00:05, 36.57it/s]  65%\|██████▌ \| 346/531 [00:10<00:04, 39.51it/s]  66%\|██████▌ \| 351/531 [00:10<00:04, 40.54it/s]  67%\|██████▋ \| 358/531 [00:10<00:04, 42.52it/s]  68%\|██████▊ \| 363/531 [00:10<00:03, 43.95it/s]  70%\|██████▉ \| 370/531 [00:10<00:03, 47.15it/s]  71%\|███████ \| 378/531 [00:11<00:03, 50.10it/s]  72%\|███████▏ \| 384/531 [00:11<00:02, 51.62it/s]  74%\|███████▍ \| 394/531 [00:11<00:02, 58.63it/s]  76%\|███████▌ \| 401/531 [00:11<00:02, 47.88it/s]  77%\|███████▋ \| 409/531 [00:11<00:02, 51.42it/s]  78%\|███████▊ \| 415/531 [00:11<00:02, 43.41it/s]  79%\|███████▉ \| 421/531 [00:11<00:02, 46.27it/s]  80%\|████████ \| 427/531 [00:12<00:02, 44.82it/s]  82%\|████████▏ \| 434/531 [00:12<00:02, 45.79it/s]  83%\|████████▎ \| 439/531 [00:12<00:02, 36.44it/s]  84%\|████████▎ \| 444/531 [00:12<00:02, 38.41it/s]  85%\|████████▍ \| 450/531 [00:12<00:01, 42.37it/s]  86%\|████████▌ \| 455/531 [00:12<00:01, 41.34it/s]  87%\|████████▋ \| 460/531 [00:12<00:01, 41.42it/s]  89%\|████████▊ \| 470/531 [00:12<00:01, 49.95it/s]  90%\|████████▉ \| 476/531 [00:13<00:01, 41.73it/s]  91%\|█████████ \| 482/531 [00:13<00:01, 42.70it/s]  92%\|█████████▏\| 487/531 [00:13<00:01, 43.99it/s]  93%\|█████████▎\| 493/531 [00:13<00:00, 47.58it/s]  94%\|█████████▍\| 499/531 [00:13<00:00, 44.26it/s]  95%\|█████████▍\| 504/531 [00:13<00:00, 39.50it/s]  96%\|█████████▌\| 509/531 [00:13<00:00, 41.50it/s]  98%\|█████████▊\| 518/531 [00:14<00:00, 48.33it/s]  99%\|█████████▉\| 525/531 [00:14<00:00, 51.81it/s] 100%\|██████████\| 531/531 [00:14<00:00, 44.89it/s]
43.045787 | Traceback (most recent call last):
43.046067 | File "/usr/local/lib/python3.6/dist-packages/deepsense/neptune/job_wrapper.py", line 113, in <module>
43.046193 | execute()
43.046346 | File "/usr/local/lib/python3.6/dist-packages/deepsense/neptune/job_wrapper.py", line 109, in execute
43.046478 | execfile(job_filepath, job_globals)
43.046593 | File "/usr/local/lib/python3.6/dist-packages/past/builtins/misc.py", line 82, in execfile
43.046707 | exec_(code, myglobals, mylocals)
43.046822 | File "main.py", line 181, in <module>
43.046935 | action()
43.047048 | File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 722, in __call__
43.047161 | return self.main(*args, **kwargs)
43.047295 | File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 697, in main
43.047454 | rv = self.invoke(ctx)
43.047573 | File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1066, in invoke
43.047688 | return _process_result(sub_ctx.command.invoke(sub_ctx))
43.047819 | File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 895, in invoke
43.047946 | return ctx.invoke(self.callback, **ctx.params)
43.048081 | File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 535, in invoke
43.048214 | return callback(*args, **kwargs)
43.048416 | File "main.py", line 153, in train_evaluate_predict_pipeline
43.048583 | _train_pipeline(pipeline_name, validation_size)
43.048723 | File "main.py", line 80, in _train_pipeline
43.048856 | pipeline.fit_transform(data)
43.048981 | File "/neptune/steps/base.py", line 92, in fit_transform
43.049092 | step_inputs[input_step.name] = input_step.fit_transform(data)
43.049217 | File "/neptune/steps/base.py", line 92, in fit_transform
43.049341 | step_inputs[input_step.name] = input_step.fit_transform(data)
43.04946 | File "/neptune/steps/base.py", line 92, in fit_transform
43.049588 | step_inputs[input_step.name] = input_step.fit_transform(data)
43.0497 | [Previous line repeated 1 more times]
43.049812 | File "/neptune/steps/base.py", line 98, in fit_transform
43.049923 | step_output_data = self._cached_fit_transform(step_inputs)
43.050033 | File "/neptune/steps/base.py", line 109, in _cached_fit_transform
43.050144 | step_output_data = self.transformer.fit_transform(**step_inputs)
43.050258 | File "/neptune/steps/base.py", line 242, in fit_transform
43.050405 | return self.transform(*args, **kwargs)
43.050531 | File "/neptune/steps/preprocessing.py", line 50, in transform
43.050657 | y_ = meta[self.y_columns].values
43.050782 | File "/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py", line 2133, in __getitem__
43.050893 | return self._getitem_array(key)
43.051018 | File "/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py", line 2177, in _getitem_array
43.051137 | indexer = self.loc._convert_to_indexer(key, axis=1)
43.051245 | File "/usr/local/lib/python3.6/dist-packages/pandas/core/indexing.py", line 1269, in _convert_to_indexer
43.051408 | .format(mask=objarr[mask]))
43.051572 | KeyError: "['file_path_contours_touching'] not in index"

**Comment by aguang1201** [comment]
You can compute metadata, by running: neptune run main.py -- prepare_metadata
You are welcome.

**Comment by jakubczakon** [comment]
Hi, this data should be uploaded today (or tomorrow).

In the meantime you could disable the contour touching output by changing the following files:
* `models.py` the model  PyTorchUNetMultitask definition uses 
` ('contour_touching', segmentation_loss, 0.1)` so comment that out.

* pipeline_config.py defines target columns
`Y_COLUMNS_MULTITASK = ['file_path_mask', 'file_path_contours', 'file_path_contours_touching', 'file_path_centers']` So just drop `file_path_contours_touching`

It should get you going right of the bat

**Comment by kamil-kaczmarek** [comment]
Hey @HAOYU-LI @mpsampat, just to let you know:

1. updated and corrected `stage1_metadata.csv` is available on the Neptune cloud.
2. if you experimenting locally (`neptune run ...`), you still need to generate masks and metadata:
```bash
neptune run main.py -- prepare_masks
neptune run main.py -- prepare_metadata
```

Cheers,
Kamil
