### ISSUE TITLE
Issue with pytorch multiprocessing

### ISSUE THREAD

**Issue by etheleon** [neptune-ml/data-science-bowl-2018#46]
Hi I'm running the latest version of the master branch c61edd4, locally. 

I kept running into a `double free or corruption` error and after searching around found that by 

installing libtcmalloc-minimal4 and adding it to the LD_PRELOAD prevents the error from occurring again. 

```
sudo apt-get install libtcmalloc-minimal4
export LD_PRELOAD="/usr/lib/libtcmalloc_minimal.so.4"
```

I'm running this in a nvidia docker container using pytorch 0.3 instead of 2. but otherwise everything else is based on the requirements.txt

this issue has been flagged out both in tensorflow, lightgbm and pytorch

https://github.com/tensorflow/tensorflow/issues/6968
https://github.com/Microsoft/LightGBM/issues/546
https://github.com/ikostrikov/pytorch-a3c/issues/2

**Comment by jakubczakon** [comment]
@etheleon thanks for the suggestion.
As I understand it solved the problem?
If so I will add it to the wiki.

**Comment by etheleon** [comment]
Yea!
