### ISSUE TITLE
MemoryError in scipy/ndimage/morphology.py

### ISSUE THREAD

**Issue by duburlan** [neptune-ml/data-science-bowl-2018#59]
I run training for 10 epochs just to make sure everything works, but when it comes to the evaluation, I get this error: https://pastebin.com/h4zu5Wd7

I pulled the latest commit from the master branch. 
Python 3.5.2
Installed packages https://pastebin.com/sBu1ZaBM

Btw, shouldn't `nr_unet_outputs`  be `4` here https://github.com/neptune-ml/data-science-bowl-2018/blob/master/neptune.yaml#L55?

**Comment by kamil-kaczmarek** [comment]
Hey @duburlan,

1. It seems that you have installed requirements in your root environment. This might cause issues. Please create virtualenv and install requirements. Explanation here: [Installation](https://github.com/neptune-ml/data-science-bowl-2018/wiki/Installation) Wiki page.
2. Yes, it must be: `nr_unet_outputs: 4`. Thank you!
3. I'm trying to reproduce your error. _Quick question_: do you control how much memory you have available for your experiment?

Best,
Kamil

**Comment by kamil-kaczmarek** [comment]
@duburlan nice! Closing issue. Please re-open in case of further problems.
